application:  a2rproject-148908
version: 1
module:demoproject
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static
